### ISSUE TITLE
Make private BTreeMap constructor public

### ISSUE THREAD

**Issue by PoslavskySV** [batterseapower/btreemap#1]
It would be really nice to make constructors in `BTreeMap` public, so the API of `BTreeMap` will be the same as for `TreeMap`. Until, if I just want to try how things got faster with a `BTreeMap` in my project, I can't replace `TreeMap` with a `BTreeMap` automatically, since I need to manually replace all constructor calls with `BTreeMap` factory methods.

**Comment by batterseapower** [comment]
You have to edit these lines anyway if you are making the change so I don’t see it as particularly problematic that you need to switch to static methods at the same time.

**Comment by PoslavskySV** [comment]
The problem is actually is that it is not possible to replace inheritors of TreeMap. E.g. one has:

```
class MyMap extends TreeMap<String, String> {
    public MyMap(Comparator<String> cmp){
        super(cmp);
    }

    // some my methods goes below
    ...
}
```
This is not possible with BTreeMap because of the private constructor (not even protected), so one need to make a huge refactoring, which is inconvenient.

**Comment by batterseapower** [comment]
I think that good style with modern Java is to use composition over inheritance (Effective Java, item 16) and either design/document for inheritance or forbid it (item 17). I haven't taken the time to design this class for inheritance, so I've chosen to forbid it.

Other popular implementations of collection types also take this approach -- e.g. Guava's ArrayListMultiMap is final.

Sorry!

**Comment by PoslavskySV** [comment]
Now I see! Thank you!
