### ISSUE TITLE
Copy / clone functionality

### ISSUE THREAD

**Issue by CodingFabian** [batterseapower/btreemap#3]
I have been looking at your library, and it looks quite neat.
Thanks.
Would you consider adding a clone() method? Use case is to freeze a map state for further processing while continuing to mutate the original map.

**Comment by batterseapower** [comment]
OK, I added `clone()` in v1.2.0. Looks like it works, but I offer no guarantees about performance!

https://bintray.com/batterseapower/maven/btreemap/1.2.0
